#!/usr/bin/bash

# INSTALL POSTGRESQL
echo "------------------------------------------"
echo "INSTALLING POSTGRESQL"
echo "------------------------------------------"

curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
sudo apt update
sudo apt install -y postgresql-client-13 libpq-dev

echo "------------------------------------------"
echo "POSTGRESQL INSTALLATION COMPLETED"
echo "------------------------------------------"

# INSTALL FRONTEND REACT DEPENDENCIES
echo "------------------------------------------"
echo "INSTALL FRONTEND REACT DEPENDENCIES"
echo "------------------------------------------"

cd frontend-react-js
npm install